### ISSUE TITLE
Wrong license?

### ISSUE THREAD

**Issue by Juul** [chdh/commons-math-interpolation#2]
Nice library but since you're porting from code that uses the Apache License 2.0 you probably aren't allowed to relicense under the MIT license.

**Comment by chdh** [comment]
The Java source file [AkimaSplineInterpolator.java](https://gitbox.apache.org/repos/asf?p=commons-math.git;a=blob;f=src/main/java/org/apache/commons/math4/analysis/interpolation/AkimaSplineInterpolator.java;h=089a7acf4c65d047bf5d1537f095c7aa069d2153;hb=HEAD) of the Apache Commons Math Library contains the following note:

> This implementation is based on the Akima implementation in the CubicSpline
> class in the Math.NET Numerics library. 

The [Math.NET Numerics Library](https://numerics.mathdotnet.com/) uses the MIT license. [CubicSpline.cs](https://github.com/mathnet/mathnet-numerics/blob/968d0798056a2b4c4cff7091241172466a0e7458/src/Numerics/Interpolation/CubicSpline.cs) contains the original code for some of the interpolation functions.

I thought that when they can change the license from MIT to Apache with the port from C# to Java, I can change it back to MIT when I port from Java to TypeScript.

The two licenses seem to be "compatible":

* [Can I use Apache licensed source code and redistribute it as MIT license?](https://www.quora.com/Can-I-use-Apache-licensed-source-code-and-redistribute-it-as-MIT-license)
"_If you create a modified or derived version of an Apache licensed work, you can distributed it under the license of your choice._"

* [Is the MIT license compatible with the Apache License Version 2 (APLv2)?](https://www.quora.com/Is-the-MIT-license-compatible-with-the-Apache-License-Version-2-APLv2)
"_Yes. In fact you can license the combined work under any license you choose._"

* [Apache license](https://www.apache.org/licenses/LICENSE-2.0)
"_You may add Your own copyright statement to Your modifications and may provide additional or different license terms and conditions for use, reproduction, or distribution of Your modifications, or for any such Derivative Works as a whole, provided Your use, reproduction, and distribution of the Work otherwise complies with the conditions stated in this License._"

Therefore I assume that I am allowed to relicense the (heavily modified) TypeScript port unter the MIT license.

**Comment by chdh** [comment]
I have added the Apache copyright and a NOTICE file. Thanks for your issue. I hope the licensing is sufficiently correct now.

**Comment by Juul** [comment]
Thank you for the quick reply and yes I believe all is in order now!
